#!/bin/bash
# telegram basic send module
# this script just send 
# location file: 
#     sudo cp telegram-send /usr/bin/telegram-send
#     sudo chmod +x /usr/bin/telegram-send
# conf=telegram-send.conf
#   this file contains bottoken and telegram users and groups
#   BOT_TOKEN is number you get when telegramuser is created
#   Usage: telegram-send bert "text message"
#
# https://github.com/bertman80/telegram_send
# made by: Bert Nieuwenampsen (2021)
version=1.0.1

basedir=$(dirname "$0")
conf=$basedir/telegram-send.conf
if [ -f "$conf" ]; then
  source $conf
else
  echo ""
  echo "Config file: " $conf " does not exist!"
  echo "Just created the file, plz update."
  echo ""
  touch $conf
  echo "# telegram friendly name = telegram code" >> $conf
  echo "BOT_TOKEN=" >> $conf
  echo "user1=123456" >> $conf
  exit 0
fi

if [ "$1" == "-c" ]; then
  # Help
  echo ""
  echo "Known contacts in: $conf"
  echo ""
  while read line; do    
    echo $line    
  done < $conf
  echo ""
  exit 0
fi

if [ "$1" == "-h" ]; then
  # Help
  echo "Help `basename $0`"
  echo "Version: $version"
  echo ""
  echo "<options>"
  echo "-h  = Help"
  echo "-c  = List contacts"
  echo ""
  echo "Usage: `basename $0` target_user \"text message\""
  echo ""
  exit 0
fi

if [ $1 ]; then
  typeset -n target=$1
  if [ -z $target ]; then
    echo "unknown target!"
    exit 0
  fi
else
  # Help
  echo ""
  echo "Help `basename $0`"
  echo "Usage: `basename $0` \"text message\""
  echo ""
  exit 0
fi

if [ -z "$2" ]
  then
    # Missing text
    echo ""
    echo "Error: Missing argument"
    echo "Usage: `basename $0` target_user \"text message\""
    echo ""
    exit 0
fi

if [ "$#" -gt 2 ]; then
    # Multiple arguments
    echo ""
    echo "Error: To many argument allowed."
    echo "Usage: `basename $0` target_user \"text message\""
    echo ""
    exit 0
fi

curl -s --data "text=$2" --data "chat_id=$target" 'https://api.telegram.org/bot'$BOT_TOKEN'/sendMessage' > /dev/null
